#ifndef __CHESTNUT_ECS_MACROS_H__
#define __CHESTNUT_ECS_MACROS_H__

#ifndef CHESTNUT_DEFAULT_STORAGE_SEGMENT_SIZE
    #define CHESTNUT_DEFAULT_STORAGE_SEGMENT_SIZE 64 //arbitrary number
#endif

#endif // __CHESTNUT_ECS_MACROS_H__